name: Firebase Deployment with Preview Channels

on:
    push:
        branches:
            - main
            - preview/*

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4  # Updated to latest version

            - name: Install Dependencies
              run: npm install

            - name: Build
              env:
                  CI: false
              run: npm run build

            - name: Archive Production Artifact
              uses: actions/upload-artifact@v4  # Updated from v3 to v4
              with:
                  name: build
                  path: build

    deploy:
        name: Deploy to Firebase Hosting
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4  # Updated to latest version

            - name: Download Build Artifact
              uses: actions/download-artifact@v4  # Updated from v3 to v4
              with:
                  name: build
                  path: build

            - name: Deploy to Preview Channel
              uses: w9jds/firebase-action@master
              with:
                  args: hosting:channel:deploy preview-${{ github.ref_name }} --expires 7d
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

            - name: Deploy to Production (if on main branch)
              if: github.ref == 'refs/heads/main'
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
